E-Commerce_Application/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using E_Commerce_Application.Models;
using Microsoft.Identity.Client;
using System.Diagnostics.Metrics;
using Microsoft.AspNetCore.Http;
using E_Commerce_Application.Data;

namespace E_Commerce_Application.Controllers
{
	
	public class CartController : Controller
	{
		private readonly ProductService _productService;

		public CartController(ProductService productService)
		{
			
			_productService = productService;
			
		}

	
		public void setCartItems(Product product, int size, int quantity, string sizeName)
		{
			var counterObject = HttpContext.Session.GetInt32("counter");
			int counter;
			if(counterObject == null) { 
				HttpContext.Session.SetInt32("counter", 0);
				counter = 0;
			}
			else
			{
				counter = (int)counterObject;
			}
			for(var i = 0; i < quantity; i++)
			{
				var name = "CartItem" + counter;
				CartItem cartItem = new CartItem(product, name, size, sizeName);
				var cartItemJson = JsonConvert.SerializeObject(cartItem);
				HttpContext.Session.SetString("CartItem" + counter, cartItemJson);
				HttpContext.Session.SetInt32("counter", counter + 1);
				counter++;
			}
	
		}
		
		
		

		public void getCartItems()
		{
			List<Object> CartList = new List<Object>();


			if (HttpContext.Session.GetInt32("counter") == null)
			{
				HttpContext.Session.SetInt32("counter", 0);

			}

			foreach (var key in HttpContext.Session.Keys)
			{

				if (key.Contains("CartItem"))
				{

					var CartItemJson = HttpContext.Session.GetString(key);
					if (CartItemJson == "")
					{
						continue;
					}
					object CartItem = JsonConvert.DeserializeObject(CartItemJson);
					if (CartItem == null)
					{
						continue;
					}
					else
					{
						CartList.Add(CartItem);
					}
				}

			}

			ViewBag.CartItems = CartList;
		}
	public async Task<IActionResult> Add()
		{
			var id = Request.Form["id"];			
			string sizeInfo = Request.Form["size"];
			var quantityString = Request.Form["quantity"];
			
			
			string[] sizeWords = sizeInfo.Split("|");
			string sizeString = sizeWords[0];
			string sizeName = sizeWords[1];

			if(quantityString == "")
			{
				quantityString = "0";
			}
			
			int quantity = Int32.Parse(quantityString);
			int size = Int32.Parse(sizeString);
		
			Product product = await _productService.GetAsync(id);
			if(quantity <= 0)
			{
				quantity = 1;
			}
			if (product == null || size == null)
			{
				return View("Error");
			}
			else
			{
				setCartItems(product, size, quantity, sizeName);
				return View();
			}
		}
		public IActionResult Remove()
		{
			var name = Request.Form["name"];
			HttpContext.Session.SetString(name, "");
			getCartItems();
			return View("Index");
		}

		public IActionResult Index()
		{
			getCartItems();
			return View();
		}

		
		

	}
}

E-Commerce_Application/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using E_Commerce_Application.Data;
using E_Commerce_Application.Models;


namespace E_Commerce_Application.Controllers
{
    [ApiController]
    [Route("Menu")]
    public class CategoryController : Controller
    {

        private readonly CategoryService _categoryService;


        public CategoryController(CategoryService categoryService) =>
            _categoryService = categoryService;

        [HttpGet]
        public async Task<IActionResult> Get(){
            var categoryList = await _categoryService.GetAsync();
            ViewBag.Categories = categoryList;
            return View("Index");
        }
  

        [HttpGet("{id:length(24)}")]
        public async Task<ActionResult<Category>> Get(string id)
        {
            var category = await _categoryService.GetAsync(id);

            if (category is null)
            {
                return NotFound();
            }
            ViewBag.Category = category;
            return category;
        }

        [HttpPost]
        public async Task<IActionResult> Post(Category newCategory)
        {
            await _categoryService.CreateAsync(newCategory);

            return CreatedAtAction(nameof(Get), new { id = newCategory.Id }, newCategory);
        }

        [HttpPut("{id:length(24)}")]
        public async Task<IActionResult> Update(string id, Category updatedCategory)
        {
            var category = await _categoryService.GetAsync(id);

            if (category is null)
            {
                return NotFound();
            }

            updatedCategory.Id = category.Id;

            await _categoryService.UpdateAsync(id, updatedCategory);

            return NoContent();
        }

        [HttpDelete("{id:length(24)}")]
        public async Task<IActionResult> Delete(string id)
        {
            var category = await _categoryService.GetAsync(id);

            if (category is null)
            {
                return NotFound();
            }

            await _categoryService.RemoveAsync(id);

            return NoContent();
        }
          public IActionResult Index()
            {
                return View();
            }
    }
}

E-Commerce_Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E_Commerce_Application</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_Commerce_Application.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E_Commerce_Application</a>
             
            
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Menu</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="About">About Us</a>
                        </li>
                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Cart" asp-action="Index">Cart</a>
                        </li>
                        
                    </ul>
                     <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Login</a>

                </div>
            </div>
        </nav>
    </header>
  
        <main role="main" class="p-0 pb-3 container-fluid">
            @RenderBody()
        </main>


    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - E_Commerce_Application - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>